- name: Setup nginx and the HTML sample file
  hosts: all
  become: yes
  vars:
    server_name: "{{ ansible_default_ipv4.address }}"
    document_root: /var/www
    app_root: html_sample
  tasks:
    - name: Update apt cache and install Nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes

    - name: Copy website files to the server's document root
      copy:
        src: "{{ app_root }}"
        dest: "{{ document_root }}"
        mode: preserve

    - name: Apply Nginx template
      template:
        src: files/nginx.conf.j2
        dest: /etc/nginx/sites-available/default
      notify: Restart Nginx

    - name: Enable new site
      file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default
        state: link
      notify: Restart Nginx

    - name: Allow all access to tcp port 80
      ufw:
        rule: allow
        port: '80'
        proto: tcp

    - name: Check Listening
      ansible.builtin.wait_for:
        port: 80
        state: "started"
        timeout: 400

    - name: Check If Working
      ansible.builtin.uri:
        url: "http://localhost"
        return_content: true
      delegate_to: "localhost"
      register: "r_working"

    - name: Check content
      ansible.builtin.assert:
        that: "'Hello' in r_working.content"

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
